VehicleMainType = {
    CAR = { name = "Car" },
    BOAT = { name = "Boat" },
    PLANE = { name = "Plane" },
    HELICOPTER = { name = "Helicopter" },
    BIKE = { name = "Bike" },
    MOTORBIKE = { name = "Motorbike" },
    TRAILER = { name = "Trailer" },
    TRAIN = { name = "Train" }
}

VehicleModelsData = {
    { modelId = 400, mainType = VehicleMainType.CAR, name = "Landstalker" },
    { modelId = 401, mainType = VehicleMainType.CAR, name = "Bravura" },
    { modelId = 402, mainType = VehicleMainType.CAR, name = "Buffalo" },
    { modelId = 403, mainType = VehicleMainType.CAR, name = "Linerunner" },
    { modelId = 404, mainType = VehicleMainType.CAR, name = "Perennial" },
    { modelId = 405, mainType = VehicleMainType.CAR, name = "Sentinel" },
    { modelId = 406, mainType = VehicleMainType.CAR, name = "Dumper" },
    { modelId = 407, mainType = VehicleMainType.CAR, name = "Fire Truck" },
    { modelId = 408, mainType = VehicleMainType.CAR, name = "Trashmaster" },
    { modelId = 409, mainType = VehicleMainType.CAR, name = "Stretch" },
    { modelId = 410, mainType = VehicleMainType.CAR, name = "Manana" },
    { modelId = 411, mainType = VehicleMainType.CAR, name = "Infernus" },
    { modelId = 412, mainType = VehicleMainType.CAR, name = "Voodoo" },
    { modelId = 413, mainType = VehicleMainType.CAR, name = "Pony" },
    { modelId = 414, mainType = VehicleMainType.CAR, name = "Mule" },
    { modelId = 415, mainType = VehicleMainType.CAR, name = "Cheetah" },
    { modelId = 416, mainType = VehicleMainType.CAR, name = "Ambulance" },
    { modelId = 417, mainType = VehicleMainType.HELICOPTER, name = "Leviathan" },
    { modelId = 418, mainType = VehicleMainType.CAR, name = "Moonbeam" },
    { modelId = 419, mainType = VehicleMainType.CAR, name = "Esperanto" },
    { modelId = 420, mainType = VehicleMainType.CAR, name = "Taxi" },
    { modelId = 421, mainType = VehicleMainType.CAR, name = "Washington" },
    { modelId = 422, mainType = VehicleMainType.CAR, name = "Bobcat" },
    { modelId = 423, mainType = VehicleMainType.CAR, name = "Mr. Whoopee" },
    { modelId = 424, mainType = VehicleMainType.CAR, name = "BF Injection" },
    { modelId = 425, mainType = VehicleMainType.HELICOPTER, name = "Hunter" },
    { modelId = 426, mainType = VehicleMainType.CAR, name = "Premier" },
    { modelId = 427, mainType = VehicleMainType.CAR, name = "Enforcer" },
    { modelId = 428, mainType = VehicleMainType.CAR, name = "Securicar" },
    { modelId = 429, mainType = VehicleMainType.CAR, name = "Banshee" },
    { modelId = 430, mainType = VehicleMainType.BOAT, name = "Predator" },
    { modelId = 431, mainType = VehicleMainType.CAR, name = "Bus" },
    { modelId = 432, mainType = VehicleMainType.CAR, name = "Rhino" },
    { modelId = 433, mainType = VehicleMainType.CAR, name = "Barracks" },
    { modelId = 434, mainType = VehicleMainType.CAR, name = "Hotknife" },
    { modelId = 435, mainType = VehicleMainType.TRAILER, name = "Trailer 1" },
    { modelId = 436, mainType = VehicleMainType.CAR, name = "Previon" },
    { modelId = 437, mainType = VehicleMainType.CAR, name = "Coach" },
    { modelId = 438, mainType = VehicleMainType.CAR, name = "Cabbie" },
    { modelId = 439, mainType = VehicleMainType.CAR, name = "Stallion" },
    { modelId = 440, mainType = VehicleMainType.CAR, name = "Rumpo" },
    { modelId = 441, mainType = VehicleMainType.CAR, name = "RC Bandit" },
    { modelId = 442, mainType = VehicleMainType.CAR, name = "Romero" },
    { modelId = 443, mainType = VehicleMainType.CAR, name = "Packer" },
    { modelId = 444, mainType = VehicleMainType.CAR, name = "Monster" },
    { modelId = 445, mainType = VehicleMainType.CAR, name = "Admiral" },
    { modelId = 446, mainType = VehicleMainType.BOAT, name = "Squalo" },
    { modelId = 447, mainType = VehicleMainType.HELICOPTER, name = "Seasparrow" },
    { modelId = 448, mainType = VehicleMainType.MOTORBIKE, name = "Pizzaboy" },
    { modelId = 449, mainType = VehicleMainType.TRAIN, name = "Tram" },
    { modelId = 450, mainType = VehicleMainType.TRAILER, name = "Trailer 2" },
    { modelId = 451, mainType = VehicleMainType.CAR, name = "Turismo" },
    { modelId = 452, mainType = VehicleMainType.BOAT, name = "Speeder" },
    { modelId = 453, mainType = VehicleMainType.BOAT, name = "Reefer" },
    { modelId = 454, mainType = VehicleMainType.BOAT, name = "Tropic" },
    { modelId = 455, mainType = VehicleMainType.CAR, name = "Flatbed" },
    { modelId = 456, mainType = VehicleMainType.CAR, name = "Yankee" },
    { modelId = 457, mainType = VehicleMainType.CAR, name = "Caddy" },
    { modelId = 458, mainType = VehicleMainType.CAR, name = "Solair" },
    { modelId = 459, mainType = VehicleMainType.CAR, name = "Berkley's RC Van" },
    { modelId = 460, mainType = VehicleMainType.PLANE, name = "Skimmer" },
    { modelId = 461, mainType = VehicleMainType.MOTORBIKE, name = "PCJ-600" },
    { modelId = 462, mainType = VehicleMainType.MOTORBIKE, name = "Faggio" },
    { modelId = 463, mainType = VehicleMainType.MOTORBIKE, name = "Freeway" },
    { modelId = 464, mainType = VehicleMainType.CAR, name = "RC Baron" },
    { modelId = 465, mainType = VehicleMainType.CAR, name = "RC Raider" },
    { modelId = 466, mainType = VehicleMainType.CAR, name = "Glendale" },
    { modelId = 467, mainType = VehicleMainType.CAR, name = "Oceanic" },
    { modelId = 468, mainType = VehicleMainType.MOTORBIKE, name = "Sanchez" },
    { modelId = 469, mainType = VehicleMainType.HELICOPTER, name = "Sparrow" },
    { modelId = 470, mainType = VehicleMainType.CAR, name = "Patriot" },
    { modelId = 471, mainType = VehicleMainType.CAR, name = "Quadbike" },
    { modelId = 472, mainType = VehicleMainType.BOAT, name = "Coastguard" },
    { modelId = 473, mainType = VehicleMainType.BOAT, name = "Dinghy" },
    { modelId = 474, mainType = VehicleMainType.CAR, name = "Hermes" },
    { modelId = 475, mainType = VehicleMainType.CAR, name = "Sabre" },
    { modelId = 476, mainType = VehicleMainType.PLANE, name = "Rustler" },
    { modelId = 477, mainType = VehicleMainType.CAR, name = "ZR-350" },
    { modelId = 478, mainType = VehicleMainType.CAR, name = "Walton" },
    { modelId = 479, mainType = VehicleMainType.CAR, name = "Regina" },
    { modelId = 480, mainType = VehicleMainType.CAR, name = "Comet" },
    { modelId = 481, mainType = VehicleMainType.BIKE, name = "BMX" },
    { modelId = 482, mainType = VehicleMainType.CAR, name = "Burrito" },
    { modelId = 483, mainType = VehicleMainType.CAR, name = "Camper" },
    { modelId = 484, mainType = VehicleMainType.BOAT, name = "Marquis" },
    { modelId = 485, mainType = VehicleMainType.CAR, name = "Baggage" },
    { modelId = 486, mainType = VehicleMainType.CAR, name = "Dozer" },
    { modelId = 487, mainType = VehicleMainType.HELICOPTER, name = "Maverick" },
    { modelId = 488, mainType = VehicleMainType.HELICOPTER, name = "News Chopper" },
    { modelId = 489, mainType = VehicleMainType.CAR, name = "Rancher" },
    { modelId = 490, mainType = VehicleMainType.CAR, name = "FBI Rancher" },
    { modelId = 491, mainType = VehicleMainType.CAR, name = "Virgo" },
    { modelId = 492, mainType = VehicleMainType.CAR, name = "Greenwood" },
    { modelId = 493, mainType = VehicleMainType.BOAT, name = "Jetmax" },
    { modelId = 494, mainType = VehicleMainType.CAR, name = "Hotring Racer" },
    { modelId = 495, mainType = VehicleMainType.CAR, name = "Sandking" },
    { modelId = 496, mainType = VehicleMainType.CAR, name = "Blista Compact" },
    { modelId = 497, mainType = VehicleMainType.HELICOPTER, name = "Police Maverick" },
    { modelId = 498, mainType = VehicleMainType.CAR, name = "Boxville" },
    { modelId = 499, mainType = VehicleMainType.CAR, name = "Benson" },
    { modelId = 500, mainType = VehicleMainType.CAR, name = "Mesa" },
    { modelId = 501, mainType = VehicleMainType.CAR, name = "RC Goblin" },
    { modelId = 502, mainType = VehicleMainType.CAR, name = "Hotring Racer 3" },
    { modelId = 503, mainType = VehicleMainType.CAR, name = "Hotring Racer 2" },
    { modelId = 504, mainType = VehicleMainType.CAR, name = "Bloodring Banger" },
    { modelId = 505, mainType = VehicleMainType.CAR, name = "Rancher Lure" },
    { modelId = 506, mainType = VehicleMainType.CAR, name = "Super GT" },
    { modelId = 507, mainType = VehicleMainType.CAR, name = "Elegant" },
    { modelId = 508, mainType = VehicleMainType.CAR, name = "Journey" },
    { modelId = 509, mainType = VehicleMainType.BIKE, name = "Bike" },
    { modelId = 510, mainType = VehicleMainType.BIKE, name = "Mountain Bike" },
    { modelId = 511, mainType = VehicleMainType.PLANE, name = "Beagle" },
    { modelId = 512, mainType = VehicleMainType.PLANE, name = "Cropduster" },
    { modelId = 513, mainType = VehicleMainType.PLANE, name = "Stuntplane" },
    { modelId = 514, mainType = VehicleMainType.CAR, name = "Tanker" },
    { modelId = 515, mainType = VehicleMainType.CAR, name = "Roadtrain" },
    { modelId = 516, mainType = VehicleMainType.CAR, name = "Nebula" },
    { modelId = 517, mainType = VehicleMainType.CAR, name = "Majestic" },
    { modelId = 518, mainType = VehicleMainType.CAR, name = "Buccaneer" },
    { modelId = 519, mainType = VehicleMainType.PLANE, name = "Shamal" },
    { modelId = 520, mainType = VehicleMainType.PLANE, name = "Hydra" },
    { modelId = 521, mainType = VehicleMainType.MOTORBIKE, name = "FCR-900" },
    { modelId = 522, mainType = VehicleMainType.MOTORBIKE, name = "NRG-500", spawnDistance = 5 },
    { modelId = 523, mainType = VehicleMainType.CAR, name = "HPV1000" },
    { modelId = 524, mainType = VehicleMainType.CAR, name = "Cement Truck" },
    { modelId = 525, mainType = VehicleMainType.CAR, name = "Towtruck" },
    { modelId = 526, mainType = VehicleMainType.CAR, name = "Fortune" },
    { modelId = 527, mainType = VehicleMainType.CAR, name = "Cadrona" },
    { modelId = 528, mainType = VehicleMainType.CAR, name = "FBI Truck" },
    { modelId = 529, mainType = VehicleMainType.CAR, name = "Willard" },
    { modelId = 530, mainType = VehicleMainType.CAR, name = "Forklift" },
    { modelId = 531, mainType = VehicleMainType.CAR, name = "Tractor" },
    { modelId = 532, mainType = VehicleMainType.CAR, name = "Harvester" },
    { modelId = 533, mainType = VehicleMainType.CAR, name = "Feltzer" },
    { modelId = 534, mainType = VehicleMainType.CAR, name = "Remington" },
    { modelId = 535, mainType = VehicleMainType.CAR, name = "Slamvan" },
    { modelId = 536, mainType = VehicleMainType.CAR, name = "Blade" },
    { modelId = 537, mainType = VehicleMainType.TRAIN, name = "Freight" },
    { modelId = 538, mainType = VehicleMainType.TRAIN, name = "Streak" },
    { modelId = 539, mainType = VehicleMainType.CAR, name = "Vortex" },
    { modelId = 540, mainType = VehicleMainType.CAR, name = "Vincent" },
    { modelId = 541, mainType = VehicleMainType.CAR, name = "Bullet" },
    { modelId = 542, mainType = VehicleMainType.CAR, name = "Clover" },
    { modelId = 543, mainType = VehicleMainType.CAR, name = "Sadler" },
    { modelId = 544, mainType = VehicleMainType.CAR, name = "Fire Truck Ladder" },
    { modelId = 545, mainType = VehicleMainType.CAR, name = "Hustler" },
    { modelId = 546, mainType = VehicleMainType.CAR, name = "Intruder" },
    { modelId = 547, mainType = VehicleMainType.CAR, name = "Primo" },
    { modelId = 548, mainType = VehicleMainType.HELICOPTER, name = "Cargobob" },
    { modelId = 549, mainType = VehicleMainType.CAR, name = "Tampa" },
    { modelId = 550, mainType = VehicleMainType.CAR, name = "Sunrise" },
    { modelId = 551, mainType = VehicleMainType.CAR, name = "Merit" },
    { modelId = 552, mainType = VehicleMainType.CAR, name = "Utility Van" },
    { modelId = 553, mainType = VehicleMainType.PLANE, name = "Nevada" },
    { modelId = 554, mainType = VehicleMainType.CAR, name = "Yosemite" },
    { modelId = 555, mainType = VehicleMainType.CAR, name = "Windsor" },
    { modelId = 556, mainType = VehicleMainType.CAR, name = "Monster 2" },
    { modelId = 557, mainType = VehicleMainType.CAR, name = "Monster 3" },
    { modelId = 558, mainType = VehicleMainType.CAR, name = "Uranus" },
    { modelId = 559, mainType = VehicleMainType.CAR, name = "Jester" },
    { modelId = 560, mainType = VehicleMainType.CAR, name = "Sultan" },
    { modelId = 561, mainType = VehicleMainType.CAR, name = "Stratum" },
    { modelId = 562, mainType = VehicleMainType.CAR, name = "Elegy" },
    { modelId = 563, mainType = VehicleMainType.HELICOPTER, name = "Raindance" },
    { modelId = 564, mainType = VehicleMainType.CAR, name = "RC Tiger" },
    { modelId = 565, mainType = VehicleMainType.CAR, name = "Flash" },
    { modelId = 566, mainType = VehicleMainType.CAR, name = "Tahoma" },
    { modelId = 567, mainType = VehicleMainType.CAR, name = "Savanna" },
    { modelId = 568, mainType = VehicleMainType.CAR, name = "Bandito" },
    { modelId = 569, mainType = VehicleMainType.TRAIN, name = "Freight Train Flatbed" },
    { modelId = 570, mainType = VehicleMainType.TRAIN, name = "Streak Train Trailer" },
    { modelId = 571, mainType = VehicleMainType.CAR, name = "Kart" },
    { modelId = 572, mainType = VehicleMainType.CAR, name = "Mower" },
    { modelId = 573, mainType = VehicleMainType.CAR, name = "Dune" },
    { modelId = 574, mainType = VehicleMainType.CAR, name = "Sweeper" },
    { modelId = 575, mainType = VehicleMainType.CAR, name = "Broadway" },
    { modelId = 576, mainType = VehicleMainType.CAR, name = "Tornado" },
    { modelId = 577, mainType = VehicleMainType.PLANE, name = "AT-400", spawnDistance = 30 },
    { modelId = 578, mainType = VehicleMainType.CAR, name = "DFT-30" },
    { modelId = 579, mainType = VehicleMainType.CAR, name = "Huntley" },
    { modelId = 580, mainType = VehicleMainType.CAR, name = "Stafford" },
    { modelId = 581, mainType = VehicleMainType.MOTORBIKE, name = "BF-400" },
    { modelId = 582, mainType = VehicleMainType.CAR, name = "Newsvan" },
    { modelId = 583, mainType = VehicleMainType.CAR, name = "Tug" },
    { modelId = 584, mainType = VehicleMainType.TRAILER, name = "Trailer (Tanker Commando)" },
    { modelId = 585, mainType = VehicleMainType.CAR, name = "Emperor" },
    { modelId = 586, mainType = VehicleMainType.MOTORBIKE, name = "Wayfarer" },
    { modelId = 587, mainType = VehicleMainType.CAR, name = "Euros" },
    { modelId = 588, mainType = VehicleMainType.CAR, name = "Hotdog" },
    { modelId = 589, mainType = VehicleMainType.CAR, name = "Club" },
    { modelId = 590, mainType = VehicleMainType.TRAIN, name = "Box Freight" },
    { modelId = 591, mainType = VehicleMainType.TRAILER, name = "Trailer 3" },
    { modelId = 592, mainType = VehicleMainType.PLANE, name = "Andromada", spawnDistance = 30 },
    { modelId = 593, mainType = VehicleMainType.PLANE, name = "Dodo" },
    { modelId = 594, mainType = VehicleMainType.CAR, name = "RC Cam" },
    { modelId = 595, mainType = VehicleMainType.BOAT, name = "Launch" },
    { modelId = 596, mainType = VehicleMainType.CAR, name = "Police LS" },
    { modelId = 597, mainType = VehicleMainType.CAR, name = "Police SF" },
    { modelId = 598, mainType = VehicleMainType.CAR, name = "Police LV" },
    { modelId = 599, mainType = VehicleMainType.CAR, name = "Police Ranger" },
    { modelId = 600, mainType = VehicleMainType.CAR, name = "Picador" },
    { modelId = 601, mainType = VehicleMainType.CAR, name = "S.W.A.T." },
    { modelId = 602, mainType = VehicleMainType.CAR, name = "Alpha" },
    { modelId = 603, mainType = VehicleMainType.CAR, name = "Phoenix" },
    { modelId = 604, mainType = VehicleMainType.CAR, name = "Glendale Damaged" },
    { modelId = 605, mainType = VehicleMainType.CAR, name = "Sadler Damaged" },
    { modelId = 606, mainType = VehicleMainType.TRAILER, name = "Baggage Trailer (covered)" },
    { modelId = 607, mainType = VehicleMainType.TRAILER, name = "Baggage Trailer (Uncovered)" },
    { modelId = 608, mainType = VehicleMainType.TRAILER, name = "Trailer (Stairs)" },
    { modelId = 609, mainType = VehicleMainType.CAR, name = "Boxville Mission" },
    { modelId = 610, mainType = VehicleMainType.TRAILER, name = "Farm Trailer" },
    { modelId = 611, mainType = VehicleMainType.TRAILER, name = "Street Clean Trailer" }
}